// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: resources/user.proto

package com.tutorials.proto;

public final class UsersProto {
  private UsersProto() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_tutorials_models_proto_User_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_tutorials_models_proto_User_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\024resources/user.proto\022\032com.tutorials.mo" +
      "dels.proto\"\225\001\n\004User\022\014\n\004name\030\001 \001(\t\022\013\n\003age" +
      "\030\002 \001(\005\0227\n\006gender\030\003 \001(\0162\'.com.tutorials.m" +
      "odels.proto.User.Gender\022\016\n\006visits\030\004 \001(\005\"" +
      ")\n\006Gender\022\010\n\004MALE\020\000\022\n\n\006FEMALE\020\001\022\t\n\005OTHER" +
      "\020\002B#\n\023com.tutorials.protoB\nUsersProtoP\001b" +
      "\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_com_tutorials_models_proto_User_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_com_tutorials_models_proto_User_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_tutorials_models_proto_User_descriptor,
        new java.lang.String[] { "Name", "Age", "Gender", "Visits", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
